; Exercise 1.9.  Each of the following two procedures defines a method for adding two positive 
; integers in terms of the procedures inc, which increments its argument by 1, and dec, 
; which decrements its argument by 1.

(define (+ a b)
  (if (= a 0)
      b
      (inc (+ (dec a) b))))

(define (+ a b)
  (if (= a 0)
      b
      (+ (dec a) (inc b))))

; Using the substitution model, illustrate the process generated by each procedure in evaluating (+ 4 5). Are these processes iterative or recursive?

;;; We wrote solutions out on paper and took a photo.
;;; We are lazy so we only used a=3, b=2 for the first definition and a=2, b=1 for the second.
;;;
;;; The first process is linear recursive. Each recursive call to '+' builds up a chain of deferred operations.
;;; 
;;; The second process is iterative process. It can  summarized by a fixed number of state variables together with a fixed rule on 
;;; how that moves from state to state.
;;;
;;; Note: Both procedures have recursive calls. That does not make them both <italics>recursive processes</italics>.